### ISSUE TITLE
Frequency Calibration variable clean-up

### ISSUE THREAD

**Issue by Greg-R** [KI3P/SDTVer050.0#14]
Frequency calibration should be controlled by a single variable from the EEPROMData struct:

EEPROMData.freqCorrectionFactor

Currently the code is a combination of EEPROMData.freqCorrectionFactor and externed variables freqCorrectionFactor and freqCorrectionFactorOld.  freqCorrectionFactorOld is nothing more than a temporary local variable.  Both of these externed variables can be removed.

All valid references to freqCorrectionFactor should be replaced by EEPROMData.freqCorrectionFactor.
The most important place to get this correct is in MenuProc.cpp; this is where the code resides which is used to perform the calibration.

73 Greg KF5N

**Comment by KI3P** [comment]
Fixed in e40b390845700d10fa6b860ee58083ab3dcdd683

Thank you Greg!
